version: '3.9'

services:
  # MS SQL Container
  ms_sql:
    container_name: database_container
    # The base image for the container
    #image: mcr.microsoft.com/mssql/server:2022-latest
    # Location of the Dockerfile to build the base image
    build:
      context: ./backend/mssql/
      dockerfile: Dockerfile
    # If the container fails, default to always restart
    restart: always
    ports:
      - '1433:1433'
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: dbtools.IO
    # Allow data persistency when starting & stopping containers
    volumes:
      - ms_sql:/var/opt/mssql
    #network_mode: 'host'

  # Vue Container
  vue:
    container_name: frontend_container
    # The base image for the container
    #image: capillae/studybuddy-vue-frontend:1.1.77
    # Location of the Dockerfile to build the base image
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - '5173:80'
    environment:
      PORT: 5173
    depends_on:
      - ms_sql


  # Flask Container
  flask:
    container_name: backend_container
    # The base image for the container
    #image: capillae/studybuddy-python-backend:1.1.16
    # Location of the Dockerfile to build the base image
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    #extra_hosts:
      #- 'host.docker.internal:host-gateway'
      #- 'localhost:1433'
    environment:
      PORT: 5000
      MSSQL_URI: mssql://localhost:1433//StudyBuddy/
      DB_NAME: StudyBuddy
    depends_on:
      - ms_sql
    #network_mode: 'host'


volumes:
  ms_sql: {}
