version: '3.9'

services:
  # MS SQL Container
  ms_sql:
    container_name: database_container
    # The base image for the container
    image: capillae/studybuddy-mssql-database:2.0.0
    # Location of the Dockerfile to build the base image
    #build:
    #  context: ./backend/mssql/
    #  dockerfile: Dockerfile
    restart: always
    ports:
      - '1433:1433'
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: dbtools.IO
    # Allow data persistency when starting & stopping containers
    volumes:
      - ms_sql:/var/opt/mssql
    restart: always
    networks:
      - app-network

  # Vue Container
  vue:
    container_name: frontend_container
    # The base image for the container
    image: capillae/studybuddy-vue-frontend:2.0.0
    # Location of the Dockerfile to build the base image
    #build:
    #  context: ./frontend/
    #  dockerfile: Dockerfile
    ports:
      - '5173:80'
    depends_on:
      - ms_sql
    restart: on-failure
    networks:
      - app-network

  # Flask Container
  flask:
    container_name: backend_container
    # The base image for the container
    image: capillae/studybuddy-python-backend:2.0.0
    # Location of the Dockerfile to build the base image
    #build:
    #  context: ./backend/
    #  dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      MSSQL_URI: mssql://localhost:1433//StudyBuddy/
      DB_NAME: StudyBuddy
    depends_on:
      - ms_sql
    restart: on-failure
    networks:
      - app-network

volumes:
  ms_sql: {}

networks:
  app-network:
    external: true
