openapi: "3.0.0"

info:
  version: "0.2"
  title: StudyBuddy API
  description: "Provides access to the StudyBuddy backend."

servers:
  - url: 127.0.0.1:5000/api
    description: Locally Hosted Development Server

paths:
  /login:
    post:
      tags: ["Account Related"]
      summary: "Submit a login request"
      description: "Send a request to the API server asking to check if the username and password values in request header match a valid user."
      operationId: login
      parameters:
      - name: username
        in: body
        required: true
        content:
          'application/json': {}
      - name: password
        in: body
        required: true
        content:
          'application/json': {}
      responses:
        200:
          description: "The user has successfully logged in."
        400:
          description: "The user has made an invalid login attempt."
        500:
          description: "Server error, problem with backend."
  /logout:
    post:
      tags: ["Account Related"]
      summary: "Submit a logout request"
      responses:
        200:
          description: "The user has successfully logged out."
        401:
          description: "The user is forbidden from performing this operation, likely because they aren't logged in currently."
        500:
          description: "Sever error, problem with the backend."
  /newuser:
    post:
      tags: ["Account Related"]
      summary: "Submit a request to create a new account."
      description: "Send a request to the API server asking to create a new user account in the database."
      operationId: newuser
      parameters:
      - name: username
        in: body
        required: true
        content:
          'application/json': {}
      - name: password
        in: body
        required: true
        content:
          'application/json': {}
      responses:
        200:
          description: "The user has successfully created an account."
        400:
          description: "The user has made a bad request; either the username is already taken, or parameters are missing."
        500:
          description: "Server error, problem with backend."
  /class/{classname}:
    get:
      tags: ["Tracking Related"]
      summary: "Get the class {classname}"
      description: "Returns the class {classname} associated with the user"
      operationId: getclass
      parameters:
        - name: session
          description: "The session cookie for the logged in user"
          in: header
          required: true
        - name: classname
          in: url
          required: true
      responses:
        200:
          description: "The user has received the class: {classname}"
          content:
            application/json:
              schemas:
                $ref: #/components/schemas/class
        400:
          description: "The user requested a class that doesn't exist"
        401:
          description: "The request maker wasn't logged in, or forgot to send the session cookie"
        500:
          description: "Internal server error, problem with backend logic or database"
  /class:
    get:
      tags: ["Tracking Related"]
      summary: "Gets all classes for the user"
      description: "Returns all the classes for the logged in user in JSON format"
      operationId: allclasses
      parameters:
        - name: session
          description: "The session cookie for the logged in user"
          in: header
          required: true
      responses:
        200:
          description: "The user has received all their classes"
          content:
            application/json:
              schemas:
                $ref: #/components/schemas/ArrayOfClasses
        401:
          description: "The request maker wasn't logged in, or forgot to send the session cookie"
        500:
          description: "Internal server error, problem with backend logic or database"
  /class/{classname}/update_time:
    post:
      tags: ["Tracking Related"]
      summary: "Increase time studied for class"
      description: "Send the server a integer (number of seconds) spent studying for the given class."
      operationId: update_time_studied
      parameters:
        - name: session
          description: "The session cookie for the logged in user"
          in: header
          required: true
        - name: classname
          in: url
          required: true
        - name: added
          in: body
          required: true
          example: "1024"
      responses:
        200:
          description: "The time in the associated class was increased successfully"
        401:
          description: "The request maker wasn't logged in, or forgot to send the session cookie"
        500:
          description: "Internal server error, problem with backend logic or database"

tags:
  - name: Account Related
    description: "Operations that pertain to a user's account management."
  - name: Tracking Related
    description: "Operations that pertain to tracking progress, classes, study time, etc."
  - name: Leveling Related
    description: "Operations that pertain to the leveling system."

components:
  schemas:
    class:
      type: object
      properties:
        cID:
          type: integer
          example: "15"
        class_Name:
          type: string
          example: "Comp 1000"
        timeslot:
          type: time
          example: "11:11"
        is_complete:
          type: integer
          example: "0"
        studyTime:
          type: float
          example: "1234.56"
        section:
          type: string
          example: "A02"
        classroom:
          type: string
          example: "EITC 405"
        prof_Name:
          type: string
          example: "Prof. Professor"
        prof_Email:
          type: string
          example: "profprof@uni.edu"
        prof_Phone:
          type: string
          example: "123-456-7890"
        prof_Office:
          type: string
          example: "EITC 406"
        prof_Hours:
          type: time
          example: "10:00"
    ArrayOfClasses:
      type: array
      properties:
        class:
          $ref: '#/components/schemas/class'