name: Backend Docker Deployment

on:
  workflow_dispatch:    # Allows this workflow to be ran manually from the Actions tab
  push:
    branches: [ main ]

env:
  IMAGE_NAME: capillae/studybuddy-python-backend
  IMAGE_TAG: 1.1.${{ github.run_number }}

jobs:
  deploy_to_docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Push Code onto VM
        uses: actions/checkout@v3.3.0

      - name: Setup Python Environment
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.11.1'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.4.1

      - name: Install Packages and Dependencies
        run:
          pip install -r requirements.txt

      - name: Login to Docker
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}


      - name: Build and Deploy Docker Image
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./backend
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
