name: Backend Unit & Regression Test

on:
  push:
    branches: [ backend ]
  pull_request:
    branches: [ main ] # Run regression tests upon PR to main
    # No integration tests as of Sprint 2, so only unit tests will be ran

    # Allows this workflow to be ran manually from the Actions tab
    workflow_dispatch:

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Push Code onto VM
        uses: actions/checkout@v3.3.0

      - name: Setup Python Environment
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.11.1'

      - name: Install Packages and Dependencies
        run:
          pip install -r requirements.txt

      - name: Run Unit Tests
        run:
          python -m unittest discover -p "*_test.py"
