name: Backend Unit Test

on:
  push:
    branches: [backend]

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Push Code onto VM
        uses: actions/checkout@v3.3.0

      - name: Setup Python Environment
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.11.1'

      - name: Run Unit Tests
        run:
          pip -m unittest
