name: Backend Unit & Regression Test

on:
  workflow_dispatch:   # Allows this workflow to be ran manually from the Actions tab
  push:
    branches: [ develop , backend ]
  pull_request:
    branches: [ main ] # Run regression tests upon PR to main
    # No integration tests as of Sprint 2, so only unit tests will be ran

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
          - 1433:1433
        env:
          SA_PASSWORD: dbtools.IO
          ACCEPT_EULA: Y

    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Push Code onto VM
        uses: actions/checkout@v3.3.0

      - name: Setup Python Environment
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.11.1'

      - name: Install Packages and Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create StudyBuddy Database
        run:
          sqlcmd -S localhost -U sa -P dbtools.IO -i ./StudyBuddy_create.sql

      - name: Run Unit Tests
        env:
          SQL_SERVER: localhost
          SQL_USER: sa
          SQL_PASSWORD: dbtools.IO
          SQL_DATABASE: StudyBuddy
        run:
          python -m unittest discover -p "*_test.py"
