name: Frontend Unit Test

on:
  push:
    branches: [frontend]

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Push Code onto VM
        uses: actions/checkout@v3.3.0

      - name: Setup Node.js Environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16

      - name: Install Packages and Build App
        run:
          npm ci
          npm run build

      - name: Run Unit Tests
          npm test
