name: Integration Test & Regression Test

on:
  workflow_dispatch:  # Allows this workflow to be ran manually from the Actions tab
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ] # Run regression tests upon PR to main

jobs:
  run_integration_test:
    runs-on: ubuntu-latest
    steps:
      - name: Push Code onto VM
        uses: actions/checkout@v3.3.0

      - name: Setup Node.js Environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16

      - name: Install Packages and Build Vue App
        working-directory: ./frontend
        run:
          npm ci
          npm run build

      - name: Setup Python Environment
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.11.1'

      - name: Install Packages and Dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create StudyBuddy Database
        run:
          sqlcmd -S tcp -U sa -P dbtools.IO -i ./StudyBuddy_create.sql

      - name: Run Unit Tests
        env:
          SQL_SERVER: localhost
          SQL_USER: sa
          SQL_PASSWORD: dbtools.IO
          SQL_DATABASE: StudyBuddy
        run:
          python -m unittest discover -p "*_test.py"

      - name: Run Integration Tests
        run:
          npm run integtest
